# Frontend Dockerfile
FROM node:22 AS build
WORKDIR /app
COPY node_modules .
COPY package.json .
COPY yarn.lock .
COPY . .
RUN yarn install
RUN yarn docker-build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]